#' Calculate goodness of fit statistics for a naive discriminative learning
#' model.
#' 
#' \code{ndlStatistics} takes an Naive Discriminary Learning model object as
#' generated by \code{\link{ndlClassify}} and calculates a range of goodness of
#' fit statistics using \code{\link{modelStatistics}}.
#' 
#' 
#' @param ndl A naive discriminative learning model fitted with
#' \code{\link{ndlClassify}}.
#' @param \dots Control arguments to be passed along to \code{modelStatistics}.
#' @return A list with the following components: \describe{
#' \item{\code{n.data}}{sum frequency of data points}
#' \item{\code{df.null}}{degrees of freedom of the Null model}
#' \item{\code{df.model}}{degrees of freedom of the fitted model}
#' \item{\code{statistics}}{a list of various measures of goodness of fit
#' calculated with \code{modelStatistics}} }
#' @author Antti Arppe and Harald Baayen
#' @seealso See also \code{\link{ndlClassify}}, \code{\link{modelStatistics}}.
#' @references Arppe, A. and Baayen, R. H. (in prep.) Statistical modeling and
#' the principles of human learning.
#' @keywords discriminative learning
#' @examples
#' 
#' data(think)
#' set.seed(314)
#' think <- think[sample(1:nrow(think),500),]
#' think.ndl <- ndlClassify(Lexeme ~ Agent + Patient, data=think)
#' ndlStatistics(think.ndl)
#' 
#' \dontrun{
#' data(dative)
#' dative.ndl <- ndlClassify(RealizationOfRecipient ~ AnimacyOfRec + DefinOfRec +
#'    PronomOfRec + AnimacyOfTheme + DefinOfTheme + PronomOfTheme, data=dative)
#' ndlStatistics(dative.ndl)
#' }
#' 
ndlStatistics = function(ndl, ...)
{ 
  pdata=acts2probs(ndl$activationMatrix)
  pmatrix=pdata$p
  predictions=pdata$predicted
  n.outcomes = nlevels(as.factor(ndl$cuesOutcomes$Outcomes))
  frequency=ndl$cuesOutcomes$Frequency
  n.data=sum(frequency)
  df.null = n.outcomes * n.data
  n.predictors = length(ndl$weightMatrix)
  df.model = df.null - n.predictors

  statistics = modelStatistics(
      observed = as.character(ndl$cuesOutcomes$Outcomes),
      predicted = predictions,
      frequency = frequency,
      p.values = pmatrix,
      n.data = n.data,
      n.predictors = n.predictors,
      outcomes = levels(as.factor(ndl$cuesOutcomes$Outcomes)),
      p.normalize = TRUE, 
      cross.tabulation = TRUE,
      p.zero.correction = 1e-10   # this can be specified according to the structure of the data
      )

  statistics <- c(list(n.data = n.data, df.null = df.null, df.model = df.model), statistics)

  class(statistics) <- c("ndlStatistics")
  return(statistics)

}
